services:
  - type: web
    name: rollerwin
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build:render
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./db/custom.db
